### ISSUE TITLE
Checksum mismatch of root.img

### ISSUE THREAD

**Issue by pradyum** [tobhe/ubuntu-asahi#139]
10-17 14:48 root         INFO     Extract: root.img
10-17 14:56 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1069, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 877, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1032, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 336, in action_install_into_free
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 456, in do_install
    self.osins.install(self.ins)
  File "/private/tmp/asahi-install/osinstall.py", line 150, in install
    self.fdcopy(sfd, dfd, zinfo.file_size)
  File "/private/tmp/asahi-install/util.py", line 211, in fdcopy
    d = sfd.read(BLOCK)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 922, in read
    data = self._read1(n)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1012, in _read1
    self._update_crc(data)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 940, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'root.img

**Comment by tobhe** [comment]
huh interesting. We did push a new image yesterday, this sounds like the zip file might have gotten corrupted somehow. I will check if it needs to be regenerated.

**Comment by tobhe** [comment]
And indeed it was. I think I fixed it for now, sorry for the inconvenience and thank you so much for the report!

Let us know if you need any help cleaning up the interrupted installation process. I recommend checking `diskutil list` to make sure you don't have any half-started Linux partitions lingering around, [more info here](https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet).
