### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by benjinne** [tobhe/ubuntu-asahi#85]
The install is failing on my Mac mini M1, I'm not sure if it's due to something I've changed, but any help is appreciated. Here's the output from the installer.log

```
01-04 08:07 root         INFO     Startup
01-04 08:07 root         INFO     Environment:
01-04 08:07 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
01-04 08:07 root         INFO       INSTALLER_DATA=https://tobhe.de/ubuntu/installer_data.json
01-04 08:07 root         INFO       REPO_BASE=https://files.tobhe.de/ubuntu
01-04 08:07 root         INFO       IPSW_BASE=None
01-04 08:07 root         INFO       EXPERT=None
01-04 08:07 root         INFO       REPORT=None
01-04 08:07 root         INFO       REPORT_TAG=None
01-04 08:07 root         INFO     Version: v0.7.1
01-04 08:07 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1058, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 111, in __init__
    self.data = json.load(open("installer_data.json"))
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
01-04 08:07 root         INFO     MSG: If you need to file a bug report, please attach the log file:
01-04 08:07 root         INFO     MSG:   /private/tmp/asahi-install/installer.log
```

**Comment by benjinne** [comment]
Edit: it appears the installer data was corrupted since it's blocked
